query Bootstrap($uid: Int!) {
  # Projects for current user
  projects(uid: $uid) {
    id
    projectName
  }

  # IDP/Settler related data
  vulnerabilityCategories {
    id
    title
  }

  idpAges {
    id
    title
  }

  idpStatuses {
    id
    title
  }

  # Aid related data
  beneficiaryAges {
    id
    title
  }

  aidSpheres {
    id
    title
    aidType
  }
}
