query Bootstrap {
  # Projects for current user
  projects {
    id
    projectName

    # Get total number of registered people
    peopleCount
    aidCount
  }

  currentUser {
    id
    email
    firstName
    lastName
    isConsultant
    isSuperuser
    isStaff

    office {
      title
    }
  }

  # IDP/Settler related data
  vulnerabilityCategories {
    id
    title
  }

  idpAges {
    id
    title
  }

  idpStatuses {
    id
    title
  }

  # Aid related data
  beneficiaryAges {
    id
    title
  }

  aidSpheres {
    id
    title
    aidType
  }
}
