mutation CreateProject($projectName: String!, $description: String!) {
  createProject(projectName: $projectName, description: $description) {
    id
    projectName
    description

    # Get total number of registered people
    peopleCount
    aidCount

    # Validation errors
    errors {
      field
      message
    }
  }
}
